#############################################################################
# Makefile for building: nexttry
# Generated by qmake (2.01a) (Qt 4.4.0) on: ?? ?? 17 23:56:24 2020
# Project:  nexttry.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-x11-4.4.0/bin/qmake -spec /usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile nexttry.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-x11-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-x11-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-x11-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-x11-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-x11-4.4.0/include/QtSql -I/usr/local/Trolltech/Qt-x11-4.4.0/include/QtSql -I/usr/local/Trolltech/Qt-x11-4.4.0/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-x11-4.4.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-x11-4.4.0//lib -lQtSql -L/usr/local/Trolltech/Qt-x11-4.4.0//lib -pthread -pthread -lQtGui -L/usr/X11R6/lib -lpng -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lglib-2.0 -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-x11-4.4.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp \
		shoppingcart.cpp \
		button.cpp \
		virtualkeyboard.cpp \
		dbsqlite.cpp \
		ttythread.cpp \
		infomanipulate.cpp \
		tty.cpp moc_dialog.cpp \
		moc_shoppingcart.cpp \
		moc_button.cpp \
		moc_virtualkeyboard.cpp \
		moc_ttythread.cpp \
		moc_infomanipulate.cpp
OBJECTS       = main.o \
		dialog.o \
		shoppingcart.o \
		button.o \
		virtualkeyboard.o \
		dbsqlite.o \
		ttythread.o \
		infomanipulate.o \
		tty.o \
		moc_dialog.o \
		moc_shoppingcart.o \
		moc_button.o \
		moc_virtualkeyboard.o \
		moc_ttythread.o \
		moc_infomanipulate.o
DIST          = /usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/lex.prf \
		nexttry.pro
QMAKE_TARGET  = nexttry
DESTDIR       = 
TARGET        = nexttry

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nexttry.pro  /usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-x11-4.4.0/lib/libQtSql.prl \
		/usr/local/Trolltech/Qt-x11-4.4.0/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-x11-4.4.0/lib/libQtGui.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile nexttry.pro
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-x11-4.4.0/lib/libQtSql.prl:
/usr/local/Trolltech/Qt-x11-4.4.0/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-x11-4.4.0/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-x11-4.4.0/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile nexttry.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/nexttry1.0.0 || $(MKDIR) .tmp/nexttry1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/nexttry1.0.0/ && $(COPY_FILE) --parents dialog.h shoppingcart.h button.h virtualkeyboard.h dbsqlite.h defdbg.h ttythread.h infomanipulate.h sqlite3.h tty.h kbd_types.h .tmp/nexttry1.0.0/ && $(COPY_FILE) --parents main.cpp dialog.cpp shoppingcart.cpp button.cpp virtualkeyboard.cpp dbsqlite.cpp ttythread.cpp infomanipulate.cpp tty.cpp .tmp/nexttry1.0.0/ && (cd `dirname .tmp/nexttry1.0.0` && $(TAR) nexttry1.0.0.tar nexttry1.0.0 && $(COMPRESS) nexttry1.0.0.tar) && $(MOVE) `dirname .tmp/nexttry1.0.0`/nexttry1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/nexttry1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dialog.cpp moc_shoppingcart.cpp moc_button.cpp moc_virtualkeyboard.cpp moc_ttythread.cpp moc_infomanipulate.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_shoppingcart.cpp moc_button.cpp moc_virtualkeyboard.cpp moc_ttythread.cpp moc_infomanipulate.cpp
moc_dialog.cpp: dialog.h
	/usr/local/Trolltech/Qt-x11-4.4.0//bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_shoppingcart.cpp: defdbg.h \
		shoppingcart.h
	/usr/local/Trolltech/Qt-x11-4.4.0//bin/moc $(DEFINES) $(INCPATH) shoppingcart.h -o moc_shoppingcart.cpp

moc_button.cpp: button.h
	/usr/local/Trolltech/Qt-x11-4.4.0//bin/moc $(DEFINES) $(INCPATH) button.h -o moc_button.cpp

moc_virtualkeyboard.cpp: virtualkeyboard.h
	/usr/local/Trolltech/Qt-x11-4.4.0//bin/moc $(DEFINES) $(INCPATH) virtualkeyboard.h -o moc_virtualkeyboard.cpp

moc_ttythread.cpp: defdbg.h \
		ttythread.h
	/usr/local/Trolltech/Qt-x11-4.4.0//bin/moc $(DEFINES) $(INCPATH) ttythread.h -o moc_ttythread.cpp

moc_infomanipulate.cpp: infomanipulate.h
	/usr/local/Trolltech/Qt-x11-4.4.0//bin/moc $(DEFINES) $(INCPATH) infomanipulate.h -o moc_infomanipulate.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		shoppingcart.h \
		defdbg.h \
		infomanipulate.h \
		dbsqlite.h \
		sqlite3.h \
		ttythread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

shoppingcart.o: shoppingcart.cpp shoppingcart.h \
		defdbg.h \
		virtualkeyboard.h \
		dialog.h \
		dbsqlite.h \
		sqlite3.h \
		button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shoppingcart.o shoppingcart.cpp

button.o: button.cpp button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o button.o button.cpp

virtualkeyboard.o: virtualkeyboard.cpp virtualkeyboard.h \
		button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o virtualkeyboard.o virtualkeyboard.cpp

dbsqlite.o: dbsqlite.cpp dbsqlite.h \
		defdbg.h \
		sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbsqlite.o dbsqlite.cpp

ttythread.o: ttythread.cpp ttythread.h \
		defdbg.h \
		tty.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ttythread.o ttythread.cpp

infomanipulate.o: infomanipulate.cpp infomanipulate.h \
		virtualkeyboard.h \
		dialog.h \
		dbsqlite.h \
		defdbg.h \
		sqlite3.h \
		button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o infomanipulate.o infomanipulate.cpp

tty.o: tty.cpp tty.h \
		defdbg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tty.o tty.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_shoppingcart.o: moc_shoppingcart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_shoppingcart.o moc_shoppingcart.cpp

moc_button.o: moc_button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_button.o moc_button.cpp

moc_virtualkeyboard.o: moc_virtualkeyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_virtualkeyboard.o moc_virtualkeyboard.cpp

moc_ttythread.o: moc_ttythread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ttythread.o moc_ttythread.cpp

moc_infomanipulate.o: moc_infomanipulate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_infomanipulate.o moc_infomanipulate.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

